### ISSUE TITLE
ListView does not render rows until scroll (iOS only)

### ISSUE THREAD

**Issue by geeknam** [tableflip/react-native-select-multiple#10]
This issue describes the problem:
https://react-native.canny.io/feature-requests/p/listview-doesnt-render-rows-until-scroll

Does anyone have similar issue?

**Comment by tanaytanay** [comment]
I have the same issue. I used https://github.com/react-community/react-navigation/issues/1238#issuecomment-297213802 for some of my other ListViews but not sure how to use it here. Did you find a fix?

**Comment by alanshaw** [comment]
Thanks for this! When landed, this PR will allow you to pass this prop:
https://github.com/tableflip/react-native-select-multiple/pull/14

**Comment by alanshaw** [comment]
You can now use the `listViewProps` prop to pass this to the list view

https://github.com/tableflip/react-native-select-multiple#properties

**Comment by trinadhkoya** [comment]
Use removeClippedSubviews={false} ,then it will work
