### ISSUE TITLE
bundling failed: "Unable to resolve module `../images/icon-checkbox.png`

### ISSUE THREAD

**Issue by Yoruba** [tableflip/react-native-select-multiple#12]
Please add checkbox images to \\node_modules\\react-native-select-multiple\\images\\ folder when using the NPM installer

bundling failed: "Unable to resolve module `../images/icon-checkbox.png`

\\node_modules\\react-native-select-multiple\\images\\icon-checkbox.png'

Thanks, Adri

**Comment by alanshaw** [comment]
Not sure I understand, I've just npm installed the module and it contains the images directory. Did you solve this?

**Comment by Yoruba** [comment]
Thanks anlanshaw, I did have solve the problem with a hack and now I use react-native-vector-icons as icon instead of the images.

You can close this issue
