### ISSUE TITLE
major bug - doesnt show up on navigating on to this view. 

### ISSUE THREAD

**Issue by jpca999** [tableflip/react-native-select-multiple#15]
![image](https://user-images.githubusercontent.com/1026325/32749288-e8f0f01a-c88c-11e7-8f12-cefe209f2f0e.png)

this issue usually happens when we use listview rather than Flatlist. 

Id suggest if you could convert the underlying to Flatlist, this issue will be resolved.

**Comment by alanshaw** [comment]
Would you be willing to send a PR?

**Comment by fazeelzama20** [comment]
@alanshaw Documentation need to be updated, there are no steps given for the installation of library.

**Comment by alanshaw** [comment]
@fazeelzama20 is that a separate issue to the above? Installation is as simple as `npm install react-native-select-multiple` - would you be willing to send a PR?

**Comment by Kikketer** [comment]
Seeing the same issue.  Anyone put in a PR yet?

<img width="351" alt="Screen Shot 2019-04-11 at 4 13 06 PM" src="https://user-images.githubusercontent.com/958042/55993438-b8ecd000-5c74-11e9-830c-5b48b0e5858c.png">

**Comment by alanshaw** [comment]
resolved in https://github.com/tableflip/react-native-select-multiple/pull/21
