### ISSUE TITLE
selectedRowStyle not effect the Text Color !!

### ISSUE THREAD

**Issue by Arshiamidos** [tableflip/react-native-select-multiple#22]
first :thanks for your component 👍 
when in want style my row with `selectedRowStyle={{backgroundColor:'gray'}}` it's OK
but when try to 

`selectedRowStyle={{backgroundColor:'gray',color:'red'}}`

 it doesn't effect the row color

**Comment by alanshaw** [comment]
You'll need to pass `selectedLabelStyle={{ color: 'red' }}` to colour the text

**Comment by Arshiamidos** [comment]
thanks 👍
