### ISSUE TITLE
Set max number of selected items

### ISSUE THREAD

**Issue by chrisehlee** [tableflip/react-native-select-multiple#23]
It would be a nice if there's an optional prop to specify maximum number of items that can be selected. I don't know if there's a workaround for this (if so i'd be glad to hear about it, need it for a project ASAP).

**Comment by chrisehlee** [comment]
Nice. Will do that soonest.

**Comment by rohit280** [comment]
how to know that how many rows are selected....i want count of all rows

**Comment by Tobbb** [comment]
added new pullrequest for this #29
