### ISSUE TITLE
Checkbox not working in Real Device 

### ISSUE THREAD

**Issue by MEsteves22** [tableflip/react-native-select-multiple#27]
If I compile my application on an android emulator everything is working as expected. However, If I compile my application on a real device, the checkbox is not working... The labels show up but not the actual checkbox so I can't select anything. Is anyone having this problem or it's just me? 
Btw, my real device has an Android version of 5.1 (API 22) and my emulator has an API level of 23.

**Comment by MEsteves22** [comment]
I solved my problem! Basically I had to use the following props to give color to the images: selectedCheckboxStyle = {{ tintColor: "black" }} and checkboxStyle = {{ tintColor: "black" }}.

**Comment by alanshaw** [comment]
Thanks for replying with the solution!
