### ISSUE TITLE
nothing on the page 

### ISSUE THREAD

**Issue by hopefullman** [tableflip/react-native-select-multiple#35]

**Comment by Tuyen4897** [comment]
I also get same issue, nothing show when i use SelectMultiple. Who can help me?

**Comment by anagar23** [comment]
https://github.com/tableflip/react-native-select-multiple/issues/31, will fix the issue.

**Comment by john-harding** [comment]
When will this be fixed?

**Comment by alanshaw** [comment]
Fixed in v2.0.1
