### ISSUE TITLE
Styling of selected checkbox does nothing

### ISSUE THREAD

**Issue by Esko918** [tableflip/react-native-select-multiple#5]
Im trying to style my selected checkbox to be a certain color but when i add styling to selectedCheckboxStyle prop it does nothing. The color only changes when i style the checkboxStyle prop. The issue is i only need the color to change if it is selected not if its not selected. SO i think there might be an issue here with your code.

**Comment by ninaadpai4** [comment]
Even I have the same issue with the styling, when I hadn't put in any style of my own it was showing correctly but a few days ago the checkboxes stopped rendering so I had to add a style of my own for the unselected/selected checkboxes and it doesn't switch between styles when you select an item.
![img_3579](https://user-images.githubusercontent.com/30378337/29828387-8ceebdec-8caa-11e7-8e0d-319c80358019.PNG)

**Comment by alanshaw** [comment]
What styles are you trying to apply? Note that the [checkbox is an image](https://github.com/tableflip/react-native-select-multiple/blob/master/src/SelectMultiple.js#L152). You might be able to use `tintColor` to change the color if that's what you're trying to do.

**Comment by mdarqummalik** [comment]
tintColor is faded? is there any solution to it ???????
![Screenshot_1660657020](https://user-images.githubusercontent.com/91880423/184893542-b1829c15-f975-49a1-8eb0-11f46fb1082b.png)

**Comment by OguzEkinci** [comment]
> tintColor is faded? is there any solution to it ??????? ![Screenshot_1660657020](https://user-images.githubusercontent.com/91880423/184893542-b1829c15-f975-49a1-8eb0-11f46fb1082b.png)

how do you do custom icon? i cant do this. not  showing my custom icon
