### ISSUE TITLE
TypeError: Cannot read property 'oneOfType' of undefined

### ISSUE THREAD

**Issue by Yoruba** [tableflip/react-native-select-multiple#9]
Please change PropTypes from the **react** component with the PropTypes from the **prop-types** component to  support  React 15.5 or higher.

```
import React, { Component } from 'react';
import PropTypes from 'prop-types';
```
TypeError: Cannot read property 'oneOfType' of undefined
at Object.<anonymous> (node_modules/react-native-select-multiple/src/SelectMultiple.js:7:30)

**Comment by alanshaw** [comment]
Fixed in 1.0.5
